spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  mvc:
    view:
      prefix: /WEB_INF/views
      suffix: .jsp